echo "Total no of arguments is $#"
echo "Script name is $0"
echo "First argument is $1"
echo "Second argument is $2"
echo "Third argument is $3"
echo "Total no of arguments is $@"
echo "Total no of arguments together is $*"
